### ISSUE TITLE
Need help for experimental case to use tokens

### ISSUE THREAD

**Issue by afzal442** [AnwarMP/ConveneAI#16]
Hi @AnwarMP and team, could you provide required tokens for credential to testing out? Wanna build sth on top of that. Thanks

**Comment by AnwarMP** [comment]
I can share how to generate them ( I probably should update the Readme).

Getting anthropic api key: 
https://console.anthropic.com/login?returnTo=%2F%3F

Getting tokens and credentials: 
I followed this tutorial for the gmail api (its the only one we support right now, feel free to add more , should be pretty straightforward) 
https://www.youtube.com/watch?v=7E3NNxeXiys&embeds_referring_euri=https%3A%2F%2Fwww.google.com%2Fsearch%3Fsca_esv%3Debc5f503c41e575a%26sxsrf%3DADLYWIIQp87xtIlBzCiHJFnI6Ivgj5Na_A%3A1730593913321%26q%3Dgmail%2Bapi%26tbm%3Dvi&source_ve_path=Mjg2NjY

This was my implementation of it so that I could test the querying abilities: https://github.com/AnwarMP/GmailClient

You will have to create a Daily token as well for the meeting rooms: https://www.daily.co/



Have fun! Thanks for checking us out

**Comment by afzal442** [comment]
Sorry @AnwarMP when I try to authenticate through gmail, I am getting issues over again and again

```
localhost refused to connect
```

credential.json is as follows

```
{"installed":{"client_id":"882417657542-php8eb0kbag52u9sipidne2n8bbt4nf0.apps.googleusercontent.com","project_id":"mypro-385411","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"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","redirect_uris":["http://localhost"]}}
```
